/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqzip.eqcoin.rpc.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FullNodeList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6835446794156352944L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FullNodeList\",\"namespace\":\"com.eqzip.eqcoin.rpc.avro\",\"fields\":[{\"name\":\"cookie\",\"type\":{\"type\":\"record\",\"name\":\"Cookie\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}]}},{\"name\":\"fullNodeList\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FullNodeList> ENCODER =
      new BinaryMessageEncoder<FullNodeList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FullNodeList> DECODER =
      new BinaryMessageDecoder<FullNodeList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FullNodeList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FullNodeList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FullNodeList>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FullNodeList to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FullNodeList from a ByteBuffer. */
  public static FullNodeList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.eqzip.eqcoin.rpc.avro.Cookie cookie;
  @Deprecated public java.nio.ByteBuffer fullNodeList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FullNodeList() {}

  /**
   * All-args constructor.
   * @param cookie The new value for cookie
   * @param fullNodeList The new value for fullNodeList
   */
  public FullNodeList(com.eqzip.eqcoin.rpc.avro.Cookie cookie, java.nio.ByteBuffer fullNodeList) {
    this.cookie = cookie;
    this.fullNodeList = fullNodeList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cookie;
    case 1: return fullNodeList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cookie = (com.eqzip.eqcoin.rpc.avro.Cookie)value$; break;
    case 1: fullNodeList = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cookie' field.
   * @return The value of the 'cookie' field.
   */
  public com.eqzip.eqcoin.rpc.avro.Cookie getCookie() {
    return cookie;
  }

  /**
   * Sets the value of the 'cookie' field.
   * @param value the value to set.
   */
  public void setCookie(com.eqzip.eqcoin.rpc.avro.Cookie value) {
    this.cookie = value;
  }

  /**
   * Gets the value of the 'fullNodeList' field.
   * @return The value of the 'fullNodeList' field.
   */
  public java.nio.ByteBuffer getFullNodeList() {
    return fullNodeList;
  }

  /**
   * Sets the value of the 'fullNodeList' field.
   * @param value the value to set.
   */
  public void setFullNodeList(java.nio.ByteBuffer value) {
    this.fullNodeList = value;
  }

  /**
   * Creates a new FullNodeList RecordBuilder.
   * @return A new FullNodeList RecordBuilder
   */
  public static com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder newBuilder() {
    return new com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder();
  }

  /**
   * Creates a new FullNodeList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FullNodeList RecordBuilder
   */
  public static com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder newBuilder(com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder other) {
    return new com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder(other);
  }

  /**
   * Creates a new FullNodeList RecordBuilder by copying an existing FullNodeList instance.
   * @param other The existing instance to copy.
   * @return A new FullNodeList RecordBuilder
   */
  public static com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder newBuilder(com.eqzip.eqcoin.rpc.avro.FullNodeList other) {
    return new com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder(other);
  }

  /**
   * RecordBuilder for FullNodeList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FullNodeList>
    implements org.apache.avro.data.RecordBuilder<FullNodeList> {

    private com.eqzip.eqcoin.rpc.avro.Cookie cookie;
    private com.eqzip.eqcoin.rpc.avro.Cookie.Builder cookieBuilder;
    private java.nio.ByteBuffer fullNodeList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cookie)) {
        this.cookie = data().deepCopy(fields()[0].schema(), other.cookie);
        fieldSetFlags()[0] = true;
      }
      if (other.hasCookieBuilder()) {
        this.cookieBuilder = com.eqzip.eqcoin.rpc.avro.Cookie.newBuilder(other.getCookieBuilder());
      }
      if (isValidValue(fields()[1], other.fullNodeList)) {
        this.fullNodeList = data().deepCopy(fields()[1].schema(), other.fullNodeList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FullNodeList instance
     * @param other The existing instance to copy.
     */
    private Builder(com.eqzip.eqcoin.rpc.avro.FullNodeList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.cookie)) {
        this.cookie = data().deepCopy(fields()[0].schema(), other.cookie);
        fieldSetFlags()[0] = true;
      }
      this.cookieBuilder = null;
      if (isValidValue(fields()[1], other.fullNodeList)) {
        this.fullNodeList = data().deepCopy(fields()[1].schema(), other.fullNodeList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'cookie' field.
      * @return The value.
      */
    public com.eqzip.eqcoin.rpc.avro.Cookie getCookie() {
      return cookie;
    }

    /**
      * Sets the value of the 'cookie' field.
      * @param value The value of 'cookie'.
      * @return This builder.
      */
    public com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder setCookie(com.eqzip.eqcoin.rpc.avro.Cookie value) {
      validate(fields()[0], value);
      this.cookieBuilder = null;
      this.cookie = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cookie' field has been set.
      * @return True if the 'cookie' field has been set, false otherwise.
      */
    public boolean hasCookie() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'cookie' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.eqzip.eqcoin.rpc.avro.Cookie.Builder getCookieBuilder() {
      if (cookieBuilder == null) {
        if (hasCookie()) {
          setCookieBuilder(com.eqzip.eqcoin.rpc.avro.Cookie.newBuilder(cookie));
        } else {
          setCookieBuilder(com.eqzip.eqcoin.rpc.avro.Cookie.newBuilder());
        }
      }
      return cookieBuilder;
    }

    /**
     * Sets the Builder instance for the 'cookie' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder setCookieBuilder(com.eqzip.eqcoin.rpc.avro.Cookie.Builder value) {
      clearCookie();
      cookieBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cookie' field has an active Builder instance
     * @return True if the 'cookie' field has an active Builder instance
     */
    public boolean hasCookieBuilder() {
      return cookieBuilder != null;
    }

    /**
      * Clears the value of the 'cookie' field.
      * @return This builder.
      */
    public com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder clearCookie() {
      cookie = null;
      cookieBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fullNodeList' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getFullNodeList() {
      return fullNodeList;
    }

    /**
      * Sets the value of the 'fullNodeList' field.
      * @param value The value of 'fullNodeList'.
      * @return This builder.
      */
    public com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder setFullNodeList(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.fullNodeList = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fullNodeList' field has been set.
      * @return True if the 'fullNodeList' field has been set, false otherwise.
      */
    public boolean hasFullNodeList() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fullNodeList' field.
      * @return This builder.
      */
    public com.eqzip.eqcoin.rpc.avro.FullNodeList.Builder clearFullNodeList() {
      fullNodeList = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FullNodeList build() {
      try {
        FullNodeList record = new FullNodeList();
        if (cookieBuilder != null) {
          record.cookie = this.cookieBuilder.build();
        } else {
          record.cookie = fieldSetFlags()[0] ? this.cookie : (com.eqzip.eqcoin.rpc.avro.Cookie) defaultValue(fields()[0]);
        }
        record.fullNodeList = fieldSetFlags()[1] ? this.fullNodeList : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FullNodeList>
    WRITER$ = (org.apache.avro.io.DatumWriter<FullNodeList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FullNodeList>
    READER$ = (org.apache.avro.io.DatumReader<FullNodeList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
