/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqzip.eqcoin.rpc.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SyncblockNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SyncblockNetwork\",\"namespace\":\"com.eqzip.eqcoin.rpc.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Cookie\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Status\",\"fields\":[{\"name\":\"cookie\",\"type\":\"Cookie\"},{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"MinerList\",\"fields\":[{\"name\":\"cookie\",\"type\":\"Cookie\"},{\"name\":\"minerList\",\"type\":\"bytes\"}]},{\"type\":\"record\",\"name\":\"FullNodeList\",\"fields\":[{\"name\":\"cookie\",\"type\":\"Cookie\"},{\"name\":\"fullNodeList\",\"type\":\"bytes\"}]},{\"type\":\"record\",\"name\":\"Height\",\"fields\":[{\"name\":\"cookie\",\"type\":\"Cookie\"},{\"name\":\"height\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"Block\",\"fields\":[{\"name\":\"cookie\",\"type\":\"Cookie\"},{\"name\":\"block\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"cookie\",\"type\":\"Cookie\"}],\"response\":\"Status\"},\"getMinerList\":{\"request\":[{\"name\":\"cookie\",\"type\":\"Cookie\"}],\"response\":\"MinerList\"},\"getFullNodeList\":{\"request\":[{\"name\":\"cookie\",\"type\":\"Cookie\"}],\"response\":\"FullNodeList\"},\"getBlockTail\":{\"request\":[{\"name\":\"cookie\",\"type\":\"Cookie\"}],\"response\":\"Height\"},\"getBlock\":{\"request\":[{\"name\":\"height\",\"type\":\"Height\"}],\"response\":\"Block\"}}}");
  /**
   */
  com.eqzip.eqcoin.rpc.avro.Status ping(com.eqzip.eqcoin.rpc.avro.Cookie cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqzip.eqcoin.rpc.avro.MinerList getMinerList(com.eqzip.eqcoin.rpc.avro.Cookie cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqzip.eqcoin.rpc.avro.FullNodeList getFullNodeList(com.eqzip.eqcoin.rpc.avro.Cookie cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqzip.eqcoin.rpc.avro.Height getBlockTail(com.eqzip.eqcoin.rpc.avro.Cookie cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqzip.eqcoin.rpc.avro.Block getBlock(com.eqzip.eqcoin.rpc.avro.Height height) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SyncblockNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqzip.eqcoin.rpc.avro.SyncblockNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqzip.eqcoin.rpc.avro.Cookie cookie, org.apache.avro.ipc.Callback<com.eqzip.eqcoin.rpc.avro.Status> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(com.eqzip.eqcoin.rpc.avro.Cookie cookie, org.apache.avro.ipc.Callback<com.eqzip.eqcoin.rpc.avro.MinerList> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(com.eqzip.eqcoin.rpc.avro.Cookie cookie, org.apache.avro.ipc.Callback<com.eqzip.eqcoin.rpc.avro.FullNodeList> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlockTail(com.eqzip.eqcoin.rpc.avro.Cookie cookie, org.apache.avro.ipc.Callback<com.eqzip.eqcoin.rpc.avro.Height> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlock(com.eqzip.eqcoin.rpc.avro.Height height, org.apache.avro.ipc.Callback<com.eqzip.eqcoin.rpc.avro.Block> callback) throws java.io.IOException;
  }
}