/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.rpc.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TransactionHashList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9141831455975995147L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionHashList\",\"namespace\":\"com.eqzip.eqcoin.rpc.avro\",\"fields\":[{\"name\":\"cookie\",\"type\":{\"type\":\"record\",\"name\":\"Cookie\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"}]}},{\"name\":\"transactionHashList\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionHashList> ENCODER =
      new BinaryMessageEncoder<TransactionHashList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionHashList> DECODER =
      new BinaryMessageDecoder<TransactionHashList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TransactionHashList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TransactionHashList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransactionHashList>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TransactionHashList to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TransactionHashList from a ByteBuffer. */
  public static TransactionHashList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.eqchains.rpc.avro.Cookie cookie;
  @Deprecated public java.nio.ByteBuffer transactionHashList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionHashList() {}

  /**
   * All-args constructor.
   * @param cookie The new value for cookie
   * @param transactionHashList The new value for transactionHashList
   */
  public TransactionHashList(com.eqchains.rpc.avro.Cookie cookie, java.nio.ByteBuffer transactionHashList) {
    this.cookie = cookie;
    this.transactionHashList = transactionHashList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cookie;
    case 1: return transactionHashList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cookie = (com.eqchains.rpc.avro.Cookie)value$; break;
    case 1: transactionHashList = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cookie' field.
   * @return The value of the 'cookie' field.
   */
  public com.eqchains.rpc.avro.Cookie getCookie() {
    return cookie;
  }

  /**
   * Sets the value of the 'cookie' field.
   * @param value the value to set.
   */
  public void setCookie(com.eqchains.rpc.avro.Cookie value) {
    this.cookie = value;
  }

  /**
   * Gets the value of the 'transactionHashList' field.
   * @return The value of the 'transactionHashList' field.
   */
  public java.nio.ByteBuffer getTransactionHashList() {
    return transactionHashList;
  }

  /**
   * Sets the value of the 'transactionHashList' field.
   * @param value the value to set.
   */
  public void setTransactionHashList(java.nio.ByteBuffer value) {
    this.transactionHashList = value;
  }

  /**
   * Creates a new TransactionHashList RecordBuilder.
   * @return A new TransactionHashList RecordBuilder
   */
  public static com.eqchains.rpc.avro.TransactionHashList.Builder newBuilder() {
    return new com.eqchains.rpc.avro.TransactionHashList.Builder();
  }

  /**
   * Creates a new TransactionHashList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionHashList RecordBuilder
   */
  public static com.eqchains.rpc.avro.TransactionHashList.Builder newBuilder(com.eqchains.rpc.avro.TransactionHashList.Builder other) {
    return new com.eqchains.rpc.avro.TransactionHashList.Builder(other);
  }

  /**
   * Creates a new TransactionHashList RecordBuilder by copying an existing TransactionHashList instance.
   * @param other The existing instance to copy.
   * @return A new TransactionHashList RecordBuilder
   */
  public static com.eqchains.rpc.avro.TransactionHashList.Builder newBuilder(com.eqchains.rpc.avro.TransactionHashList other) {
    return new com.eqchains.rpc.avro.TransactionHashList.Builder(other);
  }

  /**
   * RecordBuilder for TransactionHashList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionHashList>
    implements org.apache.avro.data.RecordBuilder<TransactionHashList> {

    private com.eqchains.rpc.avro.Cookie cookie;
    private com.eqchains.rpc.avro.Cookie.Builder cookieBuilder;
    private java.nio.ByteBuffer transactionHashList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.eqchains.rpc.avro.TransactionHashList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cookie)) {
        this.cookie = data().deepCopy(fields()[0].schema(), other.cookie);
        fieldSetFlags()[0] = true;
      }
      if (other.hasCookieBuilder()) {
        this.cookieBuilder = com.eqchains.rpc.avro.Cookie.newBuilder(other.getCookieBuilder());
      }
      if (isValidValue(fields()[1], other.transactionHashList)) {
        this.transactionHashList = data().deepCopy(fields()[1].schema(), other.transactionHashList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionHashList instance
     * @param other The existing instance to copy.
     */
    private Builder(com.eqchains.rpc.avro.TransactionHashList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.cookie)) {
        this.cookie = data().deepCopy(fields()[0].schema(), other.cookie);
        fieldSetFlags()[0] = true;
      }
      this.cookieBuilder = null;
      if (isValidValue(fields()[1], other.transactionHashList)) {
        this.transactionHashList = data().deepCopy(fields()[1].schema(), other.transactionHashList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'cookie' field.
      * @return The value.
      */
    public com.eqchains.rpc.avro.Cookie getCookie() {
      return cookie;
    }

    /**
      * Sets the value of the 'cookie' field.
      * @param value The value of 'cookie'.
      * @return This builder.
      */
    public com.eqchains.rpc.avro.TransactionHashList.Builder setCookie(com.eqchains.rpc.avro.Cookie value) {
      validate(fields()[0], value);
      this.cookieBuilder = null;
      this.cookie = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cookie' field has been set.
      * @return True if the 'cookie' field has been set, false otherwise.
      */
    public boolean hasCookie() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'cookie' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.eqchains.rpc.avro.Cookie.Builder getCookieBuilder() {
      if (cookieBuilder == null) {
        if (hasCookie()) {
          setCookieBuilder(com.eqchains.rpc.avro.Cookie.newBuilder(cookie));
        } else {
          setCookieBuilder(com.eqchains.rpc.avro.Cookie.newBuilder());
        }
      }
      return cookieBuilder;
    }

    /**
     * Sets the Builder instance for the 'cookie' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.eqchains.rpc.avro.TransactionHashList.Builder setCookieBuilder(com.eqchains.rpc.avro.Cookie.Builder value) {
      clearCookie();
      cookieBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cookie' field has an active Builder instance
     * @return True if the 'cookie' field has an active Builder instance
     */
    public boolean hasCookieBuilder() {
      return cookieBuilder != null;
    }

    /**
      * Clears the value of the 'cookie' field.
      * @return This builder.
      */
    public com.eqchains.rpc.avro.TransactionHashList.Builder clearCookie() {
      cookie = null;
      cookieBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionHashList' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getTransactionHashList() {
      return transactionHashList;
    }

    /**
      * Sets the value of the 'transactionHashList' field.
      * @param value The value of 'transactionHashList'.
      * @return This builder.
      */
    public com.eqchains.rpc.avro.TransactionHashList.Builder setTransactionHashList(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.transactionHashList = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionHashList' field has been set.
      * @return True if the 'transactionHashList' field has been set, false otherwise.
      */
    public boolean hasTransactionHashList() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionHashList' field.
      * @return This builder.
      */
    public com.eqchains.rpc.avro.TransactionHashList.Builder clearTransactionHashList() {
      transactionHashList = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionHashList build() {
      try {
        TransactionHashList record = new TransactionHashList();
        if (cookieBuilder != null) {
          record.cookie = this.cookieBuilder.build();
        } else {
          record.cookie = fieldSetFlags()[0] ? this.cookie : (com.eqchains.rpc.avro.Cookie) defaultValue(fields()[0]);
        }
        record.transactionHashList = fieldSetFlags()[1] ? this.transactionHashList : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionHashList>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionHashList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionHashList>
    READER$ = (org.apache.avro.io.DatumReader<TransactionHashList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
