/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3584256986634970846L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IO\",\"namespace\":\"com.eqchains.avro\",\"fields\":[{\"name\":\"object\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IO> ENCODER =
      new BinaryMessageEncoder<IO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IO> DECODER =
      new BinaryMessageDecoder<IO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<IO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<IO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IO>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this IO to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a IO from a ByteBuffer. */
  public static IO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.nio.ByteBuffer object;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IO() {}

  /**
   * All-args constructor.
   * @param object The new value for object
   */
  public IO(java.nio.ByteBuffer object) {
    this.object = object;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return object;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: object = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'object' field.
   * @return The value of the 'object' field.
   */
  public java.nio.ByteBuffer getObject() {
    return object;
  }

  /**
   * Sets the value of the 'object' field.
   * @param value the value to set.
   */
  public void setObject(java.nio.ByteBuffer value) {
    this.object = value;
  }

  /**
   * Creates a new IO RecordBuilder.
   * @return A new IO RecordBuilder
   */
  public static com.eqchains.avro.IO.Builder newBuilder() {
    return new com.eqchains.avro.IO.Builder();
  }

  /**
   * Creates a new IO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IO RecordBuilder
   */
  public static com.eqchains.avro.IO.Builder newBuilder(com.eqchains.avro.IO.Builder other) {
    return new com.eqchains.avro.IO.Builder(other);
  }

  /**
   * Creates a new IO RecordBuilder by copying an existing IO instance.
   * @param other The existing instance to copy.
   * @return A new IO RecordBuilder
   */
  public static com.eqchains.avro.IO.Builder newBuilder(com.eqchains.avro.IO other) {
    return new com.eqchains.avro.IO.Builder(other);
  }

  /**
   * RecordBuilder for IO instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IO>
    implements org.apache.avro.data.RecordBuilder<IO> {

    private java.nio.ByteBuffer object;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.eqchains.avro.IO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.object)) {
        this.object = data().deepCopy(fields()[0].schema(), other.object);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing IO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.eqchains.avro.IO other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.object)) {
        this.object = data().deepCopy(fields()[0].schema(), other.object);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'object' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getObject() {
      return object;
    }

    /**
      * Sets the value of the 'object' field.
      * @param value The value of 'object'.
      * @return This builder.
      */
    public com.eqchains.avro.IO.Builder setObject(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.object = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'object' field has been set.
      * @return True if the 'object' field has been set, false otherwise.
      */
    public boolean hasObject() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'object' field.
      * @return This builder.
      */
    public com.eqchains.avro.IO.Builder clearObject() {
      object = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IO build() {
      try {
        IO record = new IO();
        record.object = fieldSetFlags()[0] ? this.object : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IO>
    WRITER$ = (org.apache.avro.io.DatumWriter<IO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IO>
    READER$ = (org.apache.avro.io.DatumReader<IO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
