/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MinerNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MinerNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"IO\",\"fields\":[{\"name\":\"object\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"cookie\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getMinerList\":{\"request\":[],\"response\":\"IO\"},\"getFullNodeList\":{\"request\":[],\"response\":\"IO\"},\"sendNewBlock\":{\"request\":[{\"name\":\"block\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getTransactionIndexList\":{\"request\":[],\"response\":\"IO\"},\"getTransactionList\":{\"request\":[{\"name\":\"transactionIndexList\",\"type\":\"IO\"}],\"response\":\"IO\"}}}");
  /**
   */
  com.eqchains.avro.IO ping(com.eqchains.avro.IO cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getMinerList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getFullNodeList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO sendNewBlock(com.eqchains.avro.IO block) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getTransactionIndexList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getTransactionList(com.eqchains.avro.IO transactionIndexList) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MinerNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqchains.avro.MinerNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqchains.avro.IO cookie, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendNewBlock(com.eqchains.avro.IO block, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionIndexList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionList(com.eqchains.avro.IO transactionIndexList, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
  }
}