/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

@org.apache.avro.specific.AvroGenerated
public interface MinerNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MinerNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"O\",\"fields\":[{\"name\":\"o\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"c\",\"type\":\"O\"}],\"response\":\"O\"},\"getMinerList\":{\"request\":[],\"response\":\"O\"},\"getFullNodeList\":{\"request\":[],\"response\":\"O\"},\"broadcastNewBlock\":{\"request\":[{\"name\":\"b\",\"type\":\"O\"}],\"response\":\"O\"},\"getTransactionIndexList\":{\"request\":[],\"response\":\"O\"},\"getTransactionList\":{\"request\":[{\"name\":\"transactionIndexList\",\"type\":\"O\"}],\"response\":\"O\"}}}");
  /**
   */
  com.eqchains.avro.O ping(com.eqchains.avro.O c);
  /**
   */
  com.eqchains.avro.O getMinerList();
  /**
   */
  com.eqchains.avro.O getFullNodeList();
  /**
   */
  com.eqchains.avro.O broadcastNewBlock(com.eqchains.avro.O b);
  /**
   */
  com.eqchains.avro.O getTransactionIndexList();
  /**
   */
  com.eqchains.avro.O getTransactionList(com.eqchains.avro.O transactionIndexList);

  @SuppressWarnings("all")
  public interface Callback extends MinerNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqchains.avro.MinerNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqchains.avro.O c, org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void broadcastNewBlock(com.eqchains.avro.O b, org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionIndexList(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionList(com.eqchains.avro.O transactionIndexList, org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
  }
}