/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

@org.apache.avro.specific.AvroGenerated
public interface SyncblockNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SyncblockNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"O\",\"fields\":[{\"name\":\"o\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"c\",\"type\":\"O\"}],\"response\":\"O\"},\"getMinerList\":{\"request\":[],\"response\":\"O\"},\"getFullNodeList\":{\"request\":[],\"response\":\"O\"},\"getBlockTail\":{\"request\":[],\"response\":\"O\"},\"getBlock\":{\"request\":[{\"name\":\"h\",\"type\":\"O\"}],\"response\":\"O\"}}}");
  /**
   */
  com.eqchains.avro.O ping(com.eqchains.avro.O c);
  /**
   */
  com.eqchains.avro.O getMinerList();
  /**
   */
  com.eqchains.avro.O getFullNodeList();
  /**
   */
  com.eqchains.avro.O getBlockTail();
  /**
   */
  com.eqchains.avro.O getBlock(com.eqchains.avro.O h);

  @SuppressWarnings("all")
  public interface Callback extends SyncblockNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqchains.avro.SyncblockNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqchains.avro.O c, org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlockTail(org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlock(com.eqchains.avro.O h, org.apache.avro.ipc.Callback<com.eqchains.avro.O> callback) throws java.io.IOException;
  }
}