/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SyncblockNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SyncblockNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"IO\",\"fields\":[{\"name\":\"object\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"cookie\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getMinerList\":{\"request\":[],\"response\":\"IO\"},\"getFullNodeList\":{\"request\":[],\"response\":\"IO\"},\"getBlockTail\":{\"request\":[],\"response\":\"IO\"},\"getBlock\":{\"request\":[{\"name\":\"height\",\"type\":\"IO\"}],\"response\":\"IO\"}}}");
  /**
   */
  com.eqchains.avro.IO ping(com.eqchains.avro.IO cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getMinerList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getFullNodeList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getBlockTail() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getBlock(com.eqchains.avro.IO height) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SyncblockNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqchains.avro.SyncblockNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqchains.avro.IO cookie, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlockTail(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBlock(com.eqchains.avro.IO height, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
  }
}