/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqchains.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface TransactionNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TransactionNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"IO\",\"fields\":[{\"name\":\"object\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"cookie\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getMinerList\":{\"request\":[],\"response\":\"IO\"},\"sendTransaction\":{\"request\":[{\"name\":\"transactionRPC\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getID\":{\"request\":[{\"name\":\"readableAddress\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getAccount\":{\"request\":[{\"name\":\"ID\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getMaxNonce\":{\"request\":[{\"name\":\"ID\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getBalance\":{\"request\":[{\"name\":\"ID\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getSignHash\":{\"request\":[{\"name\":\"ID\",\"type\":\"IO\"}],\"response\":\"IO\"},\"getTransactionList\":{\"request\":[{\"name\":\"ID\",\"type\":\"IO\"}],\"response\":\"IO\"}}}");
  /**
   */
  com.eqchains.avro.IO ping(com.eqchains.avro.IO cookie) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getMinerList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO sendTransaction(com.eqchains.avro.IO transactionRPC) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getID(com.eqchains.avro.IO readableAddress) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getAccount(com.eqchains.avro.IO ID) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getMaxNonce(com.eqchains.avro.IO ID) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getBalance(com.eqchains.avro.IO ID) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getSignHash(com.eqchains.avro.IO ID) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqchains.avro.IO getTransactionList(com.eqchains.avro.IO ID) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends TransactionNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqchains.avro.TransactionNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqchains.avro.IO cookie, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendTransaction(com.eqchains.avro.IO transactionRPC, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getID(com.eqchains.avro.IO readableAddress, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getAccount(com.eqchains.avro.IO ID, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMaxNonce(com.eqchains.avro.IO ID, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getBalance(com.eqchains.avro.IO ID, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getSignHash(com.eqchains.avro.IO ID, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionList(com.eqchains.avro.IO ID, org.apache.avro.ipc.Callback<com.eqchains.avro.IO> callback) throws java.io.IOException;
  }
}